server:
  port: 7011
spring:
  datasource:
    url: jdbc:postgresql://192.168.173.239:5432/middleground?stringtype=unspecified
    username: dbadmin
    password: runlion-mid-123
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 15
    initialSize: 3
    maxWait: 5000
    minIdle: 3
    timeBetweenEvictionRunsMillis: 90000
    minEvictableIdleTimeMillis: 1800000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  application:
    name: scalog-task

mybatis:
  mapperLocations: classpath:mapper/*.xml
